const path = require("path");
const fs = require("fs");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const CopyWebpackPlugin = require("copy-webpack-plugin");
const webpack = require("webpack");

// Read MCP_API_TOKEN from root .env (generated by scripts/generate-token.mjs).
// Fail fast at build time if missing — prevents shipping an unauthenticated bundle.
function loadToken() {
  const envPath = path.resolve(__dirname, "../../.env");
  if (!fs.existsSync(envPath)) {
    throw new Error(
      `[generate-token] .env not found at ${envPath}.\n` +
      `Run: node scripts/generate-token.mjs`
    );
  }
  const match = fs.readFileSync(envPath, "utf8").match(/^MCP_API_TOKEN=(.+)$/m);
  if (!match) {
    throw new Error(
      `[generate-token] MCP_API_TOKEN not found in ${envPath}.\n` +
      `Run: node scripts/generate-token.mjs`
    );
  }
  return match[1].trim();
}

module.exports = (env, argv) => {
const mcpToken = loadToken();
return {
	entry: "./src/app.ts",
	output: {
		filename: "bundle.js",
		path: path.resolve(__dirname, "dist"),
		clean: true,
	},
	devtool: "source-map",
	mode: "development",
	module: {
		rules: [
			{
				test: /\.ts$/,
				use: "ts-loader",
				exclude: /node_modules/,
			},
		],
	},
	resolve: {
		extensions: [".ts", ".js"],
	},
	plugins: [
		new webpack.DefinePlugin({
			__MCP_TOKEN__: JSON.stringify(mcpToken),
		}),
		new HtmlWebpackPlugin({
			template: "./src/index.html",
		}),
		new CopyWebpackPlugin({
			patterns: [
				{
					from: "manifest.xml",
					to: "../manifest.xml",
				},
				{
					from: "assets/**/*",
					to: "assets/[name][ext]",
				},
			],
		}),
	],
	devServer: {
		port: 3001,
		host: "127.0.0.1",
		hot: true,
		// Office Add-ins need HTTPS in production; localhost HTTP works for dev
		// In production, use a reverse proxy with valid TLS
	},
};
};
